import React, { useState, useCallback } from "react";
import { createEditor, Transforms } from "slate";
import { Slate, Editable, withReact } from "slate-react";

import { Leaf, Element as SlateElement } from "../components/rederElement";

import Head from "next/head";
import Toolbar from "../components/Toolbar";

import styles from "../styles/Home.module.css";
import buttonSwitcher from "../helpers/buttonSwitch";

import initialValue from "../Stores/initialValue.json";

export default function Home() {
  const [editor] = useState(() => withReact(createEditor()));

  const onHandleKeyDown = (event) => {
    if (!event.ctrlKey) {
      return;
    }
    buttonSwitcher(event, editor, Transforms);
  };

  const renderElement = useCallback((props) => <SlateElement {...props} />, []);
  const renderLeaf = useCallback((props) => <Leaf {...props} />, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Slate Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Rich Text Editor</h1>
        <div className={styles.slateContainer}>
          <Slate editor={editor} value={initialValue}>
            <Toolbar />
            <Editable
              renderElement={renderElement}
              renderLeaf={renderLeaf}
              onKeyDown={onHandleKeyDown}
            />
          </Slate>
        </div>
      </main>
    </div>
  );
}
